name: unreal ci

on: 
  workflow_dispatch:
  push:
    paths: 
      - unreal/Puerts/Source/**
  pull_request:
    paths: 
      - unreal/Puerts/Source/**

env:
  V8: "https://github.com/puerts/backend-v8/releases/download/V8_8.4.371.19_0323/v8_bin_8.4.371.19.tgz"
  Engine: "https://github.com/chexiongsheng/Mini427/releases/download/v1.0.0/Mini427_wami.tgz"

jobs:
  
  window_ci:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
    - name: Prepare
      shell: msys2 {0}
      run: |
        wget -O v8lib.tgz -q  ${{env.V8}} 
        tar xvfz v8lib.tgz -C unreal/Puerts/ThirdParty
        wget -O temp.tgz -q  ${{env.Engine}} 
        tar xvfz temp.tgz
        ls Engine
        mkdir output
    - name: Build
      run: |
        Engine\Build\BatchFiles\RunUAT.bat BuildPlugin -Plugin="unreal\Puerts\Puerts.uplugin" -Package="output" -Rocket -TargetPlatforms=Win64 -VS2019
        
        
  android_ci:
    name: Android
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
    - name: Prepare
      shell: msys2 {0}
      run: |
        wget -O v8lib.tgz -q  ${{env.V8}} 
        tar xvfz v8lib.tgz -C unreal/Puerts/ThirdParty
        wget -O temp.tgz -q  ${{env.Engine}} 
        tar xvfz temp.tgz
        ls Engine
        mkdir output
    - name: SetupAndroid
      run: |
        Engine\Extras\Android\SetupAndroid.bat
        chcp 65001 #set code page to utf-8
        echo "NDKROOT=C:\Android\android-sdk\ndk\21.4.7075529" >> $env:GITHUB_ENV
    - name: Build
      run: |
        Engine\Build\BatchFiles\RunUAT.bat BuildPlugin -Plugin="unreal\Puerts\Puerts.uplugin" -Package="output" -Rocket -TargetPlatforms=Android -VS2019

  mac_ios_ci:
    name: Mac and IOS
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      shell: bash
      run: |
        wget -O v8lib.tgz -q  ${{env.V8}} 
        tar xvfz v8lib.tgz -C unreal/Puerts/ThirdParty
        wget -O temp.tgz -q  ${{env.Engine}} 
        tar xvfz temp.tgz
        mkdir output
        sudo xcode-select -s /Applications/Xcode_12.5.1.app
    - name: Build
      shell: bash
      run: |
        Engine/Build/BatchFiles/RunUAT.sh BuildPlugin -Plugin=unreal/Puerts/Puerts.uplugin -Package=output -Rocket -TargetPlatforms=Mac+IOS